par = int(input('digite um numero:'))
impar = int(input('digite um numero:'))
print('a soma é', par+impar)
print(' a subtração é', par-impar)
print(' a multiplicação é',par*impar)
print(' a divisao é', par/impar)
